/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import React from 'react';
import Footer from '../../component/footer/Footer';
import Header from '../../component/header/Header';
import PageTitle from '../../component/pagetitle/PageTitle';
import styles from './Contact.module.scss';

const Contact = () => {
  return (
    <>
      <Head>
        <title>大丸白衣</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <main>
        <section className={styles.contactSection}>
          <div className={styles.contactInner}>
            <PageTitle titleH1='お問い合わせ' titleH2='contact' />
            <div className='flex flex-col justify-content-center mt-12'>
              <p className='text-xl mx-auto '>
                大丸白衣へのお問い合わせはこちらから
              </p>
              <p className='mt-5 mx-auto text-center'>
                電話・FAXでのお問い合わせの場合
                <br />
                TEL. 06-6632-0891　FAX.06-6411-9200
                <br />
                ※土・日・祝除く 9:00〜18:00
                <br />
                メールでのお問い合わせは下記フォームにてどうぞ。
              </p>
            </div>
            <form
              className={`${styles.contactForm} flex flex-col my-6 mx-auto text-md`}
            >
              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='campany'>会社名・屋号</label>
                <input type='text' id='campany' className={`w-full`} />
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='campany-kana'>
                  会社名・屋号
                  <br />
                  （フリガナ）
                </label>
                <input type='text' id='campany-kana' className={`w-full`} />
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='department'>部署名</label>
                <input type='text' id='department' className={`w-full`} />
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='name'>ご担当者様</label>
                <div className={`flex w-full`}>
                  <input type='text' id='name' className={`w-6/12`} />
                  <span className={`mx-1`}></span>
                  <input type='text' id='name' className={`w-6/12`} />
                </div>
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='name-kana'>
                  ご担当者様
                  <br />
                  （フリガナ）
                </label>
                <div className={`flex w-full`}>
                  <input type='text' id='name-kana' className={`w-6/12`} />
                  <span className={`mx-1`}></span>
                  <input type='text' id='name-kana' className={`w-6/12`} />
                </div>
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='tel'>電話番号</label>
                <div className={`flex items-center`}>
                  <input type='text' id='tel' className={`w-full md:w-3/12`} />
                  <span className={`mx-1 mb-1`}>-</span>
                  <input type='text' id='tel' className={`w-full md:w-3/12`} />
                  <span className={`mx-1 mb-1`}>-</span>
                  <input type='text' id='tel' className={`w-full md:w-3/12 `} />
                </div>
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='fax'>FAX番号</label>
                <div className={`flex items-center`}>
                  <input type='text' id='fax' className={`w-full md:w-3/12`} />
                  <span className={`mx-1 mb-1`}>-</span>
                  <input type='text' id='fax' className={`w-full md:w-3/12`} />
                  <span className={`mx-1 mb-1`}>-</span>
                  <input type='text' id='fax' className={`w-full md:w-3/12`} />
                </div>
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='mail'>メールアドレス</label>
                <input type='mail' id='mail' className={`w-full`} />
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='subject'>件名</label>
                <input type='text' id='subject' className={`w-full`} />
              </div>

              <div className={`${styles.contactFormBox}`}>
                <label htmlFor='content'>お問い合わせ内容</label>
                <textarea id='content' className={`w-full`}></textarea>
              </div>
              <div className={`flex justify-center mt-6`}>
                <div
                  className={`flex items-center justify-center w-40 h-8 rounded-md text-white bg-sky-600 hover:bg-sky-500 cursor-pointer`}
                >
                  送信
                </div>
              </div>
            </form>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Contact;
