/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import React from 'react';
import Footer from '../../component/footer/Footer';
import Header from '../../component/header/Header';
import styles from './Company.module.scss';

const Company = () => {
  return (
    <>
      <Head>
        <title>大丸白衣</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Serif+JP&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Header />
      <main>
        <section className={styles.companySection}>
          <div className={styles.companyInner}>
            <div className={styles.companyHeading}>
              <h1 className={styles.companyH1}>会社概要</h1>
              <h2 className={styles.companyH2}>Company Profile</h2>
              <ul className={styles.companyList}>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>会社名</div>
                  <div className={styles.companyRight}>株式会社大丸白衣</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>本社</div>
                  <div className={styles.companyRight}>
                    <p className={styles.p}>
                      〒542-0073
                      <br />
                      大阪市中央区日本橋2丁目4番17号
                      <br />
                      営業部｜Tel : 06-6632-0891（代表） FAX : 06-6641-9200
                      <br />
                      ショップ｜Tel : 06-6641-4629
                    </p>
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>神戸支店</div>
                  <div className={styles.companyRight}>
                    <p className={styles.p}>
                      〒650-0021
                      <br />
                      神戸市中央区三宮町3丁目9番17号
                      <br />
                      Tel : 078-391-4629 FAX : 078-321-0747
                    </p>
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>自社工場</div>
                  <div className={styles.companyRight}>
                    <p className={styles.p}>
                      〒779-3131
                      <br />
                      徳島市下町本丁
                      <br />
                      Tel : 0886-44-0301
                    </p>
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>配送センター</div>
                  <div className={styles.companyRight}>
                    <p className={styles.p}>
                      〒542-0073
                      <br />
                      大阪市中央区日本橋1丁目22番15号
                      <br />
                      Tel : 06-6641-0891
                    </p>
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>営業内容</div>
                  <div className={styles.companyRight}>
                    ユニフォーム製造販売
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>資本金</div>
                  <div className={styles.companyRight}>3000万円</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>従業員</div>
                  <div className={styles.companyRight}>50名</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>創業</div>
                  <div className={styles.companyRight}>昭和6年10月</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>設立</div>
                  <div className={styles.companyRight}>昭和31年12月27日</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>代表取締役社長</div>
                  <div className={styles.companyRight}>中尾 仁美</div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>取引銀行</div>
                  <div className={styles.companyRight}>
                    三菱UFJ銀行 心斎橋支店　／　三井住友銀行
                    難波支店　／　関西みらい銀行 難波支店
                  </div>
                </li>
                <li className={styles.companyItem}>
                  <div className={styles.companyLeft}>決算期</div>
                  <div className={styles.companyRight}>毎年2月末日</div>
                </li>
              </ul>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Company;
