import Head from "next/head";
import React from "react";
import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import PageTitle from "../../components/pagetitle/PageTitle";

const Greetings = () => {
  return (
    <>
      <Head>
        <title>大丸白衣 | 代表挨拶</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <section className="inner p-6">
          <PageTitle titleH1="代表挨拶" titleH2="Message" />
          <article className={`my-12 text-sm`}>
            <p className={`mb-6`}>
              昭和6年、私たち大丸白衣は、その名の通り白衣専門店として大阪の地で創業しました。
            </p>
            <p className={`mb-6`}>
              それから90余年、豊かで成熟した社会へと大きく様変わりしていく中で、私たちは白衣＝ユニフォームという広い視野に立ち、これまで培ってきた経験と伝統を基盤としながら、新たに果たすべき役割や可能性について問い続け、新たな商品開発を行ってきました。
            </p>
            <p className={`mb-6`}>
              その領域は、製造業、流通、医療、サービスなど多岐にわたります。
            </p>
            <p className={`mb-6`}>
              私たちの使命は、それぞれの分野で日々変わりゆくニーズを的確に捉え、現場で働く皆様にとって最良のユニフォームづくりに徹すること。堅牢なだけでなく、動きやすさや着心地のよさも重視し、あらゆる用途・環境に応じたユニフォームを提供しています。そして、時代の潮流を意識したファッション性をプラスすることも忘れません。
            </p>
            <p className={`mb-6`}>
              すべては、ユニフォームに袖を通すお客様にいきいきと快適に過ごしていただくために―――。
            </p>
            <p className={`mb-6`}>
              私たち大丸白衣は、今後も上質なユニフォームづくりを通して人と社会に貢献できるよう、不断の努力を続けてまいります。
            </p>
            <div className={"text-right"}>
              代表取締役社長
              <br />
              中尾 仁美
            </div>
          </article>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Greetings;
