import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Header from "../../components/header/Header";
import Information from "../../components/information/Information";
import styles from "./serenade.module.scss";

interface Props {
  posts: {
    id: string;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
    revisedAt: string;
    title: string;
    category: [];
    date: string;
  }[];
}

const Serenade: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Serenade 大丸白衣</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <div
          className={`${styles.serenadeContainer} mx-auto flex flex-col lg:flex-row`}
        >
          <div className={`w-full lg:w-7/12`}>
            <img src="./images/serenade-top-image.jpg" />
          </div>
          <div
            className={`w-full lg:w-5/12 mt-12 lg:mt-0 flex flex-col items-center justify-center`}
          >
            <div>
              <h1 className={`text-3xl`}>強く、美しい人へ。</h1>
              <p className={`mt-10 text-sm`}>
                わたしたちは知っています。
                <br />
                目の前の守るべき人を支えたい。力になりたい。
                <br />
                その一心で、くる日もくる日も
                <br />
                かけがえのない命と向き合っている。
                <br />
                心と体にすべてでたたかっている、その姿を。
                <br />
                そして、懸命な献身の内側に
                <br />
                ほんとうの美しさがあることを。
                <br />
                貴方には、その美しさにふさわしい
                <br />
                ほんとうにいいものを身に着けてほしい。
                <br />
                そんな思いを込めて、
                <br />
                リスペクトとともにこの一着をお届けします。
              </p>
            </div>
          </div>
        </div>
        <Information posts={posts} directory={"/serenade/news"} />
      </main>
    </>
  );
};

export default Serenade;

export async function getStaticProps() {
  const option: {} = {
    headers: {
      "X-MICROCMS-API-KEY": "d6bb628f48544d69a1adb92e4c51261c636f",
    },
  };
  const res = await fetch(`https://serenade.microcms.io/api/v1/news`, option);
  const resJson = await res.json();
  const posts = resJson.contents;
  return {
    props: {
      posts,
    },
  };
}
