/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import PageTitle from "../../components/pagetitle/PageTitle";

interface Props {
  products: {
    id: string;
    productCode: string;
    productNumber: string;
    productName: string;
    image1: {
      url: string;
    };
    price: number;
  }[];
}

const Products: NextPage<Props> = ({ products }) => {
  const router = useRouter();
  useEffect(() => {
    router.push("/");
  });
  return (
    <>
      <Head>
        <title>大丸白衣 | 商品情報</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <section className={`m-full mb-28`}>
          <div className={`inner p-6`}>
            <PageTitle titleH1="商品一覧" titleH2="Product List" />
            <div className={`flex flex-row mt-16`}>
              {products.map((product) => (
                <div key={product.id}>
                  <div>
                    <div className={`w-56`}>
                      <a href={`/products/${product.id}`}>
                        <img src={product.image1.url} width="250" />
                      </a>
                    </div>
                    <div>
                      {product.productNumber} {product.productName}
                    </div>
                    <div>価格 ￥{product.price} + 税</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Products;

export async function getStaticProps() {
  const option: {} = {
    headers: {
      "X-MICROCMS-API-KEY": "d33f8465c4814bbc9f2f3567f8664e5d9dfd",
    },
  };
  const res = await fetch(
    `https://zbo8y0zyr4.microcms.io/api/v1/products`,
    option
  );
  const resJson = await res.json();
  const products = resJson.contents;
  return {
    props: {
      products,
    },
  };
}
