/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import React from 'react';

const Csr = () => {
  return (
    <>
      <Head>
        <title>大丸白衣</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <div style={{ width: '100%', textAlign: 'center' }}>CSR</div>
      </main>
    </>
  );
};

export default Csr;
